# Generated by Django 3.1.4 on 2020-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0003_auto_20201209_1334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votevalue",
            name="value",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
