# Generated by Django 3.1.4 on 2020-12-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20201124_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='changed_at',
            new_name='edit_at',
        ),
    ]
