# Generated by Django 3.1.4 on 2020-12-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20201210_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_locked',
            new_name='is_locked',
        ),
    ]
