# Generated by Django 3.1.4 on 2020-12-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0005_auto_20201210_1358"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
