name: Check Pull Requests

on:
  pull_request

jobs:

  build:
    env:
      DATABASE_PASSWORD: 'my_db_password'
      SECRET_KEY: 'my_secret_key'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: 'bullette_db'
          POSTGRES_USER: 'bullette_db_admin'
          POSTGRES_PASSWORD: 'my_db_password'
        ports:
          - 5432:5432

    steps:

      - uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          
      - name: pre-commit
        run: pipenv run pre-commit --all-files
        
      - name: Running tests
        run: pipenv run pytest
